### ISSUE TITLE
Revisar modificación gestion_reservas

### ISSUE THREAD

**Issue by MLeyton75** [MLeyton75/Tarea-Seman8-PWII#1]
Estimado Pablo, favor revisar modificación de gestion_reservas

Slds.

MLA

**Comment by Mcdriaga** [comment]
Hola Marcelo, acuso recibo, procedo a corregir.

Saludos,
Pablo.

**Comment by MLeyton75** [comment]
Hola Pablo
Estamos OK.

Slds.

Marcelo
